FROM quay.io/jupyter/datascience-notebook:notebook-7.2.1

LABEL org.opencontainers.image.vendor="Ministry of Justice" \
      org.opencontainers.image.authors="Analytical Platform (analytical-platform@digital.justice.gov.uk)" \
      org.opencontainers.image.title="Jupyter Data Science Notebook" \
      org.opencontainers.image.description="Jupyter Data Science Notebook image for Analytical Platform" \
      org.opencontainers.image.url="https://github.com/ministryofjustice/analytical-platform-jupyterlab"
